### ISSUE TITLE
Update repo "About" description (not just GitHub Pages anymore)

### ISSUE THREAD

**Issue by denisecase** [Vishalreddy114/FSA3#1]
In your repo About section, you say:

This a full-stack web app that we want to develop. Hosted app link on GitHub pages is provided.

Rather than the previous GitHub Pages (client-side) app, you now have a Full-Stack app, hosted on Heroku. You might want to update your description. 

Nice work!

**Comment by rohith0696** [comment]
We have updated it. 
Thank You, Dr. Case.
